### ISSUE TITLE
[Kafka - Latest commit strategy] Last messages from Kafka process very slowly, as each one causes a poll() with 1-second timeout to fetch nothing new

### ISSUE THREAD

**Issue by smolloy-moog** [smallrye/smallrye-reactive-messaging#1507]
When we are processing messages from kafka using a simple @Incoming annotation, we see that as soon as the kafka topic is exhausted, and all the messages are loaded into the in-memory "buffer" in KafkaRecordStreamSubscription.queue, each request for another message (aka each invocation of our annotated method) will FIRST poll() to Kafka, wait for the timeout (1 second), find no additional items, then return an item from the in-memory buffer to the consumer.  Given the default value of the max.poll.records being 500, this means that if you are unlucky enough to pull the last 500 messages from kafka in one poll(), each and every one of those 500 messages will process at a rate of 1-per-second, as they each will first invoke poll(), find nothing new, then return a single item from the buffer (which has lots).

We don't have a patch to submit, nor an easy test case to submit here, so all I have is this explanation for now.  I think "going back to the Kafka well for more" doesn't need to happen until the in-memory buffer of already-fetched-messages is either depleted, or "nearing depletion" (subjective, I know, sorry). :)  Or, that the "going back to the Kafka well for more" always happens on a parallel thread that does not stop the dispatch() call from continuing to drain the in-memory buffer of messages.

I think this is due to a direct, blocking, call to poll() in io.smallrye.reactive.messaging.kafka.impl.KafkaRecordStream.KafkaRecordStreamSubscription#request - instead of putting the work onto the worker thread like other places, it makes a direct call to poll() if the state is not currently polling, but won't call dispatch() ... poll() will only call dispatch() after the steps in pollUni run, which is where the call to Kafka occurs.

Hopefully this is understandable as to what we're hitting and why, and where we think the pinch is.

**Comment by ozangunalp** [comment]
@smolloy-moog thanks for the description. I'll try to reproduce it. 
At the top of my mind, message dispatches run always on vert.x context and poll's run always on the polling thread.
Except _I think_ for the first call to the poll, which should originate from a request call.

**Comment by itzg** [comment]
I'm on the same team as @smolloy-moog. It's probably good to mention that we're using Quarkus 2.3.1, which seems to use 3.9.1 of smallrye-reactive-messaging-kafka. Perhaps there's a new version that fixes this? Understandably, it's probably hard to answer that without a reproducer yet.

**Comment by cescoffier** [comment]
Ah ah! Thanks! We fixed an issue in that area recently. So I would recommend using reactive messaging 3.10 or 3.11. It might be already fixed.

**Comment by smolloy-moog** [comment]
Well, I can say "the latest version still has the same behavior" and, you are right (and I was wrong), the blocking call to poll() that I pointed to only happens on the first iteration, and subsequent calls all hop right to dispatch().  Yet, the poll(timeout) call to Kafka still gates our per-message consumption rates, so now we're focusing on maybe some interaction of the commit ack() call and the poll(timeout) calls - we're thinking maybe the ack() (which calls commit() on the Kafka client) may get blocked by the poll(timeout) call on the same client, and if that's the case, it's "after our method" that the pause would be happening, but only when 1. the kafka consumer has no messages to fetch and has to wait the full 1 second, and 2. the offset being committed is > than what was previously committed, and 3. assumes that commit() is blocked by poll(timeout)

**Comment by smolloy-moog** [comment]
OK, so, good news - it was correct that the ack()->commit() call was waiting on poll(timeout), and, switching from "latest" commit strategy to "throttled", where the commits are done "every once in a while, but not on EVERY message" immediately "solved" the issue (more like "avoided").  The "solutions" to using "latest" commit strategy in combination with poll(timeout) seem very complex, so for now, I think going with "throttled" strategy will be the best way to provide consistent throughput, albeit with a slight "risk" of the buffered commits being lost on an unexpected JVM exit.

**Comment by smolloy-moog** [comment]
I am not sure if I should close this issue, or rename it to "risks of using 'latest' strategy when consuming the last messages from Kafka topic"?  The issue is still there when these conditions and settings are combined, but I am not sure I can call it a bug now, more like a limitation of how Kafka client forces us to only do "one thing at a time".

**Comment by ozangunalp** [comment]
Using the "latest" commit strategy explains the issue you are having. The Kafka consumer is not thread-safe, so we are using a single thread to poll and commit offsets. I don't know yet if there is a better way of implementing the latest commit strategy.

**Comment by cescoffier** [comment]
_latest_ is dangerous and should not be used. It's still there because there are use cases, but, use it at your own risk. It's not using Kafka "the recommended way".

**Comment by ozangunalp** [comment]
Looking at this again, the problem arises from the fact that the latest commit strategy does sync commit on the polling thread, therefore waits for the polling thread (blocked on the Consumer#poll for incoming records).

I think it makes sense to do an async commit without waiting for the result and only log if there is a commit error. It'll make the latest commit strategy more usable.

Note that this means the message will be acked, no matter what, without waiting for the commit result.

@smolloy-moog @itzg any thoughts?

**Comment by itzg** [comment]
That sounds great @ozangunalp and thanks for following through on this issue. BTW, I had reproduced the issue with the following repo:

https://github.com/itzg/try-quarkus-kafka-commit-latest
